version: "3"

services:
# Base Apache kafka image to be used to construct the broker and zookeeper.
  base-kafka:
    build: ./base-kafka
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/base-kafka:${BUILD_VERSION}
    profiles:
      - build

# Base consumer image used to construct Akamai SIEM consumer.
  base-consumer:
    build: base-consumer
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/base-akamai-siem-consumer:${BUILD_VERSION}
    profiles:
      - build

# Base processor image used to constructor processors to consume Akamai SIEM events.
  base-processor:
    build: base-processor
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/base-akamai-siem-processor:${BUILD_VERSION}
    profiles:
      - build

# Consumer that generated mock events. Uncomment to use it.
  consumer:
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/base-akamai-siem-consumer:${BUILD_VERSION}
    container_name: consumer
    hostname: consumer
#    volumes:
#      - ./base-consumer/etc/consumer.conf:/home/consumer/etc/consumer.conf
#    depends_on:
#      - scheduler
    profiles:
      - run

# Consumer that collects from Akamai SIEM. Uncomment to use it.
#  consumer:
#    build:
#      context: ./consumer
#      args:
#        - REPOSITORY_URL=${REPOSITORY_URL}
#        - REPOSITORY_ID=${REPOSITORY_ID}
#        - BUILD_VERSION=${BUILD_VERSION}
#    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/akamai-siem-consumer:${BUILD_VERSION}
#    container_name: consumer
#    hostname: consumer
#    volumes:
#      - ~/.edgerc:/home/consumer/.edgerc
#      - ./consumer/etc/consumer.conf:/home/consumer/etc/consumer.conf
#    depends_on:
#      - scheduler
#    profiles:
#      - build
#      - run

# Processor that stores events in files. Uncomment to use it.
#  processor:
#    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/base-akamai-siem-processor:${BUILD_VERSION}
#    container_name: processor
#    hostname: processor
#    volumes:
#      - ./base-processor/etc/processor.conf:/home/processor/etc/processor.conf
#    depends_on:
#      - scheduler
#    profiles:
#      - run

# Processor that stores events in Apache kafka. Uncomment to use it.
  processor:
    build:
      context: processor-kafka
      args:
        - REPOSITORY_URL=${REPOSITORY_URL}
        - REPOSITORY_ID=${REPOSITORY_ID}
        - BUILD_VERSION=${BUILD_VERSION}
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/akamai-siem-processor-kafka:${BUILD_VERSION}
    container_name: processor
    hostname: processor
#    volumes:
#      - ./processor-kafka/etc/processor.conf:/home/processor/etc/processor.conf
    depends_on:
      - scheduler
    profiles:
      - build
      - run

# Scheduler that defines the jobs for the consumer.
  scheduler:
    build: ./scheduler
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/akamai-siem-scheduler:${BUILD_VERSION}
    container_name: scheduler
    hostname: scheduler
#    ports:
#      - "1883:1883"
#    volumes:
#      - ./scheduler/etc/scheduler.conf:/home/scheduler/etc/scheduler.conf
#      - ./scheduler/etc/mosquitto.conf:/home/schedyler/etc/mosquitto.conf
    profiles:
      - build
      - run

# Zookeeper image used to control the broker instances.
  zookeeper:
    build:
      context: ./kafka/zookeeper
      args:
        - REPOSITORY_URL=${REPOSITORY_URL}
        - REPOSITORY_ID=${REPOSITORY_ID}
        - BUILD_VERSION=${BUILD_VERSION}
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/zookeeper:${BUILD_VERSION}
    container_name: zookeeper
    hostname: zookeeper
#    ports:
#      - "2181:2181"
#      - "8080:8080"
#    volumes:
#      - ./kafka/zookeeper/etc/zookeeper.properties:/home/kafka/etc/zookeeper.properties
    profiles:
      - run
      - build

# Broker image used to receive the events collected.
  broker:
    build:
      context: ./kafka/broker
      args:
        - REPOSITORY_URL=${REPOSITORY_URL}
        - REPOSITORY_ID=${REPOSITORY_ID}
        - BUILD_VERSION=${BUILD_VERSION}
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/kafka-broker:${BUILD_VERSION}
    container_name: broker
    hostname: broker
#    ports:
#      - "9092:9092"
#    volumes:
#      - ./kafka/broker/etc/server.properties:/home/kafka/etc/server.properties
    depends_on:
      - zookeeper
    profiles:
      - run
      - build

# UI for Apache Kafka.
  broker-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    container_name: broker-ui
    hostname: broker-ui
    ports:
      - "8080:8080"
    depends_on:
      - broker
    profiles:
      - run

# Logstash image used to collect the events from kafka.
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.12.1
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash/etc/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - broker
    profiles:
      - run