version: "3"

services:
# Consumer that collects from Akamai SIEM. Uncomment to use it.
  consumer:
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/akamai-siem-consumer:${BUILD_VERSION}
    container_name: consumer
    hostname: consumer
    volumes:
      - ./consumer/etc/.edgerc:/home/consumer/.edgerc
      - ./consumer/etc/consumer.conf:/home/consumer/etc/consumer.conf
    depends_on:
      - scheduler

# Processor that stores events in Apache kafka. Uncomment to use it.
  processor:
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/akamai-siem-processor-kafka:${BUILD_VERSION}
    container_name: processor
    hostname: processor
    volumes:
      - ./processor-kafka/etc/processor.conf:/home/processor/etc/processor.conf
    depends_on:
      - scheduler

# Scheduler that defines the jobs for the consumer.
  scheduler:
    build: ./scheduler
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/akamai-siem-scheduler:${BUILD_VERSION}
    container_name: scheduler
    hostname: scheduler
    volumes:
      - ./scheduler/etc/scheduler.conf:/home/scheduler/etc/scheduler.conf

# Zookeeper image used to control the broker instances.
  zookeeper:
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/zookeeper:${BUILD_VERSION}
    container_name: zookeeper
    hostname: zookeeper
    volumes:
      - ./kafka/zookeeper/etc/zookeeper.properties:/home/kafka/etc/zookeeper.properties

# Broker image used to receive the events collected.
  broker:
    image: ${REPOSITORY_URL}/${REPOSITORY_ID}/kafka-broker:${BUILD_VERSION}
    container_name: broker
    hostname: broker
    volumes:
      - ./kafka/broker/etc/server.properties:/home/kafka/etc/server.properties
    depends_on:
      - zookeeper

# UI for Apache Kafka.
  broker-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    container_name: broker-ui
    hostname: broker-ui
    ports:
      - "8080:8080"
    depends_on:
      - broker

# Logstash image used to collect the events from kafka.
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.12.1
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash/etc/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - broker