name: Docker Image CI

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v3

      - name: Build
        run: ./build.sh

      - name: Publish
        env:
          REPOSITORY_PASSWORD: ${{ secrets.REPOSITORY_PASSWORD }}
        run: ./publish.sh
